export const objectDefinitions = [
    "part",
    "beam",
    "welding",
    "bolt",
    'spiral_beam',
    'column',
    'twinprofile',
    'contourplate',
    'bentplate',
    'loftedplate',
    'foldedplate',
    'concrete_beam',
    'concrete_spiral_beam',
    'concrete_column',
    'pad_footing',
    'strip_footing',
    'concrete_panel',
    'concrete_slab',
    'loftedslab',
    'rebar',
    'surfacing',
    'singledrawing',
    'assemblydrawing',
    'gadrawing',
    'multidrawing',
    'castunitdrawing',
    'project', 'phase',
    'reference_part',
    'steelassembly',
    'precastassembly',
    'insituassembly',
    'grid',
    'grid_plane',
    'task',
    'pour_object',
    'pour_unit',
    'pour_break',
    'item',
    'concrete_item',
    'surface_object'
];
export const tabDefinition = "tab_page";

exports.objectDefinitions = objectDefinitions;
exports.tabDefinition = tabDefinition;